---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - CONNECTION=local
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install ansible
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container ${BASE_IMAGE} /bin/bash
        # Workaround: Docker connection plugin of Ansible requires that
        # Python is installed at specified path(/usr/bin/python) in the target container
        - docker exec container ln -s /usr/local/bin/python /usr/bin/python
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - CONNECTION=docker
        - BASE_IMAGE=python:2-slim
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        # The image of Alpine Linux doesn't have bash.
        - docker run -it -d --name container ${BASE_IMAGE} /bin/sh
        # Workaround: Docker connection plugin of Ansible requires that
        # Python is installed at specified path(/usr/bin/python) in the target container
        - docker exec container ln -s /usr/local/bin/python /usr/bin/python
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - CONNECTION=docker
        - BASE_IMAGE=python:2-alpine

install:
  - pip install ansible

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} -vvvv
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
