---
# tasks file for python-requirements(On OSX)
# No task is needed.
- name: Install latest OpenSSL
  homebrew: name=openssl state=latest update_homebrew=yes
# TODO: Now, change status of this task is always true
- name: Use OpenSSL of Homebrew instead of pre-installed one
  homebrew: name=openssl state=linked install_options="--force"
